name: multimodal-across-domains-gaze-target-detection
channels:
  - pytorch
  - defaults
dependencies:
  - pip:
    - click==8.1.3
    - cycler==0.11.0
    - docker-pycreds==0.4.0
    - fonttools==4.34.4
    - gitdb==4.0.9
    - gitpython==3.1.27
    - imageio==2.16.0
    - joblib==1.1.0
    - kiwisolver==1.4.4
    - matplotlib==3.5.2
    - networkx==2.8.5
    - packaging==21.3
    - pandas==1.4.3
    - pathtools==0.1.2
    - promise==2.3
    - protobuf==3.20.1
    - psutil==5.9.1
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - python-dotenv==0.20.0
    - pytz==2022.1
    - pywavelets==1.3.0
    - pyyaml==6.0
    - scikit-image==0.19.3
    - scikit-learn==1.1.2
    - scipy==1.9.0
    - sentry-sdk==1.9.3
    - setproctitle==1.3.1
    - shortuuid==1.0.9
    - smmap==5.0.0
    - threadpoolctl==3.1.0
    - tifffile==2022.8.8
    - timm==0.6.7
    - wandb==0.13.1
